//// <auto-generated />
//using System;
//using FastaApp.Models;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//namespace FastaApp.Migrations
//{
//    [DbContext(typeof(AppDbContext))]
//    [Migration("20230909135010_IdentityAdded")]
//    partial class IdentityAdded
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("Relational:MaxIdentifierLength", 128)
//                .HasAnnotation("ProductVersion", "5.0.17")
//                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//            modelBuilder.Entity("FastaApp.Models.Car", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("BodyStyle")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Brand")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Color")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("Condition")
//                        .HasColumnType("int");

//                    b.Property<string>("Features")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("Gps")
//                        .HasColumnType("int");

//                    b.Property<string>("ImageUrl")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("LicensePlate")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<double>("Mileage")
//                        .HasColumnType("float");

//                    b.Property<string>("Model")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<decimal>("PricePerDay")
//                        .HasColumnType("decimal(18,2)");

//                    b.Property<string>("RentalLocation")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ThumbNailImageUrl")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("Transmission")
//                        .HasColumnType("int");

//                    b.Property<int>("Year")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.ToTable("Cars");

//                    b.HasData(
//                        new
//                        {
//                            Id = "fd4ef50b-1191-4f54-b156-916e4dbb8b08",
//                            BodyStyle = "Sedan",
//                            Brand = "Toyota",
//                            Color = "Silver",
//                            Condition = 1,
//                            Features = "Air Conditioner,Bluetooth,Backup Camera",
//                            Gps = 0,
//                            ImageUrl = "https://i.pinimg.com/236x/74/61/4d/74614d884940788ce8d1a6ef46fcb8a9.jpg",
//                            LicensePlate = "ABC123",
//                            Mileage = 10000.0,
//                            Model = "Corolla",
//                            PricePerDay = 15000.00m,
//                            RentalLocation = "Downtown Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 1,
//                            Year = 2022
//                        },
//                        new
//                        {
//                            Id = "79fb5057-69b9-4ec9-9282-730d13d86378",
//                            BodyStyle = "Coupe",
//                            Brand = "Ford",
//                            Color = "Red",
//                            Condition = 0,
//                            Features = "Air Conditioner,Leather Seats,Apple CarPlay",
//                            Gps = 1,
//                            ImageUrl = "https://img.freepik.com/premium-vector/car_27088-93.jpg?w=826",
//                            LicensePlate = "DEF456",
//                            Mileage = 5000.0,
//                            Model = "Mustang",
//                            PricePerDay = 25080.00m,
//                            RentalLocation = "Airport Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 0,
//                            Year = 2023
//                        },
//                        new
//                        {
//                            Id = "5fdb7407-9c9c-4f4c-a8b5-5f21a3852809",
//                            BodyStyle = "SUV",
//                            Brand = "Honda",
//                            Color = "Blue",
//                            Condition = 1,
//                            Features = "All-Wheel Drive,Air Conditioner,Sunroof",
//                            Gps = 0,
//                            ImageUrl = "https://img.freepik.com/premium-vector/realistic-vector-blue-city-car-coupe-sport-transportation-isolated-background_33869-3203.jpg?w=826",
//                            LicensePlate = "XYZ789",
//                            Mileage = 15000.0,
//                            Model = "CR-V",
//                            PricePerDay = 13789.00m,
//                            RentalLocation = "Suburb Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 1,
//                            Year = 2021
//                        },
//                        new
//                        {
//                            Id = "b47cb55e-1586-47d4-80d6-a305284b519d",
//                            BodyStyle = "SUV",
//                            Brand = "Chevrolet",
//                            Color = "Black",
//                            Condition = 0,
//                            Features = "Air Conditioner,Third-Row Seating,Rear Entertainment System",
//                            Gps = 0,
//                            ImageUrl = "https://img.freepik.com/premium-vector/car-illustration_74218-174.jpg?w=826",
//                            LicensePlate = "MNO102",
//                            Mileage = 8000.0,
//                            Model = "Tahoe",
//                            PricePerDay = 30090.00m,
//                            RentalLocation = "City Center Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 1,
//                            Year = 2022
//                        },
//                        new
//                        {
//                            Id = "9e7f2fd7-5338-428a-af7c-a652ff8738e3",
//                            BodyStyle = "Sedan",
//                            Brand = "Nissan",
//                            Color = "White",
//                            Condition = 0,
//                            Features = "Air Conditioner,Keyless Entry,Lane Departure Warning",
//                            Gps = 1,
//                            ImageUrl = "https://img.freepik.com/free-vector/white-sedan-car-isolated-white-vector_53876-67413.jpg?w=740&t=st=1693468993~exp=1693469593~hmac=85da748d4aaa3d7e6b355f713443f4d83c1b7657c921d615f0700aa0b2a91c24",
//                            LicensePlate = "PQR345",
//                            Mileage = 3500.0,
//                            Model = "Altima",
//                            PricePerDay = 12000.00m,
//                            RentalLocation = "Residential Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 2,
//                            Year = 2023
//                        },
//                        new
//                        {
//                            Id = "cc94e49a-5fb3-4056-b499-00c878c99bb7",
//                            BodyStyle = "SUV",
//                            Brand = "BMW",
//                            Color = "Dark Grey",
//                            Condition = 1,
//                            Features = "Air Conditioner,Virtual Cockpit,Adaptive Cruise Control",
//                            Gps = 0,
//                            ImageUrl = "https://img.freepik.com/free-vector/black-sedan-car-isolated-white-vector_53876-64403.jpg?w=740&t=st=1693469071~exp=1693469671~hmac=e9294ad93de6cf4e47d7fcee1d010df6fd0c1c41b64dc6508bb1e91bcad4ea8b",
//                            LicensePlate = "STU678",
//                            Mileage = 12000.0,
//                            Model = "X5",
//                            PricePerDay = 27790.00m,
//                            RentalLocation = "Luxury Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 1,
//                            Year = 2022
//                        },
//                        new
//                        {
//                            Id = "fd45b881-3bfc-4ba8-8228-45c0a4a41779",
//                            BodyStyle = "Crossover",
//                            Brand = "Hyundai",
//                            Color = "Silver",
//                            Condition = 0,
//                            Features = "Air Conditioner,Panoramic Roof,Advanced Driver Assistance",
//                            Gps = 1,
//                            ImageUrl = "https://img.freepik.com/free-vector/white-hatchback-car-isolated-white-vector_53876-67619.jpg?w=740&t=st=1693469151~exp=1693469751~hmac=42020cd6b47cea4989913352d633ee1f077224ae04331702d18a80b9978f4160",
//                            LicensePlate = "VWX901",
//                            Mileage = 4000.0,
//                            Model = "Tuscon",
//                            PricePerDay = 12900.00m,
//                            RentalLocation = "Urban Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 1,
//                            Year = 2023
//                        },
//                        new
//                        {
//                            Id = "a7775604-d52d-4761-9be8-5facba647222",
//                            BodyStyle = "Sedan",
//                            Brand = "Mercedes Benz",
//                            Color = "Black",
//                            Condition = 1,
//                            Features = "Air Conditioner,Apple CarPlay,Lane Keeping Assistance",
//                            Gps = 0,
//                            ImageUrl = "https://img.freepik.com/free-vector/black-sedan-car-isolated-white-vector_53876-64403.jpg?w=740&t=st=1693469250~exp=1693469850~hmac=f3510a48665977358efbfbbb4feda40e4219fbb151376d0201abff0be083f5e0",
//                            LicensePlate = "XYZ234",
//                            Mileage = 9000.0,
//                            Model = "C-Class",
//                            PricePerDay = 18000.00m,
//                            RentalLocation = "Downtown Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 1,
//                            Year = 2021
//                        },
//                        new
//                        {
//                            Id = "9880c842-9bef-4fdb-90b0-26d070b91acb",
//                            BodyStyle = "Wagon",
//                            Brand = "Subaru",
//                            Color = "Green",
//                            Condition = 0,
//                            Features = "Air Conditioner,Leather Seats,Premium Sound System",
//                            Gps = 0,
//                            ImageUrl = "https://img.freepik.com/premium-vector/realistic-green-sport-two-tone-luxury-car-set-grey-metallic-background-vector_33869-3705.jpg?w=826",
//                            LicensePlate = "ABC567",
//                            Mileage = 2500.0,
//                            Model = "Outback",
//                            PricePerDay = 13000.00m,
//                            RentalLocation = "Suburb Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 2,
//                            Year = 2023
//                        },
//                        new
//                        {
//                            Id = "bc54f743-ccfb-4561-b50f-667415f785df",
//                            BodyStyle = "Sedan",
//                            Brand = "Audi",
//                            Color = "Blue",
//                            Condition = 1,
//                            Features = "Air Conditioner,All-Wheel Drive,Roof Rack",
//                            Gps = 1,
//                            ImageUrl = "https://img.freepik.com/free-vector/blue-hatchback-car-isolated-white-vector_53876-67408.jpg?w=740&t=st=1693469399~exp=1693469999~hmac=32c8b4fcec147544bfb4919c72de1bc1229d202c4bd18741bdcb065f908b2be3",
//                            LicensePlate = "DEF678",
//                            Mileage = 7500.0,
//                            Model = "A4",
//                            PricePerDay = 28470.00m,
//                            RentalLocation = "Airport Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 1,
//                            Year = 2022
//                        });
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Name")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("NormalizedName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.HasKey("Id");

//                    b.HasIndex("NormalizedName")
//                        .IsUnique()
//                        .HasDatabaseName("RoleNameIndex")
//                        .HasFilter("[NormalizedName] IS NOT NULL");

//                    b.ToTable("AspNetRoles");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("RoleId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("Id");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetRoleClaims");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<int>("AccessFailedCount")
//                        .HasColumnType("int");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Email")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<bool>("EmailConfirmed")
//                        .HasColumnType("bit");

//                    b.Property<bool>("LockoutEnabled")
//                        .HasColumnType("bit");

//                    b.Property<DateTimeOffset?>("LockoutEnd")
//                        .HasColumnType("datetimeoffset");

//                    b.Property<string>("NormalizedEmail")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("NormalizedUserName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("PasswordHash")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("PhoneNumber")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("PhoneNumberConfirmed")
//                        .HasColumnType("bit");

//                    b.Property<string>("SecurityStamp")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("TwoFactorEnabled")
//                        .HasColumnType("bit");

//                    b.Property<string>("UserName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.HasKey("Id");

//                    b.HasIndex("NormalizedEmail")
//                        .HasDatabaseName("EmailIndex");

//                    b.HasIndex("NormalizedUserName")
//                        .IsUnique()
//                        .HasDatabaseName("UserNameIndex")
//                        .HasFilter("[NormalizedUserName] IS NOT NULL");

//                    b.ToTable("AspNetUsers");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("Id");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserClaims");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                {
//                    b.Property<string>("LoginProvider")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ProviderKey")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ProviderDisplayName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("LoginProvider", "ProviderKey");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserLogins");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                {
//                    b.Property<string>("UserId")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("RoleId")
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("UserId", "RoleId");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetUserRoles");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                {
//                    b.Property<string>("UserId")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("LoginProvider")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("Name")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("Value")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("UserId", "LoginProvider", "Name");

//                    b.ToTable("AspNetUserTokens");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
