// <auto-generated />
//using System;
//using FastaApp.Models;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//namespace FastaApp.Migrations
//{
//    [DbContext(typeof(AppDbContext))]
//    partial class AppDbContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("Relational:MaxIdentifierLength", 128)
//                .HasAnnotation("ProductVersion", "5.0.17")
//                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//            modelBuilder.Entity("FastaApp.Models.Car", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("BodyStyle")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Brand")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Color")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("Condition")
//                        .HasColumnType("int");

//                    b.Property<string>("Description")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Features")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("Gps")
//                        .HasColumnType("int");

//                    b.Property<string>("ImageUrl")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("LicensePlate")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<double>("Mileage")
//                        .HasColumnType("float");

//                    b.Property<string>("Model")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<decimal>("PricePerDay")
//                        .HasColumnType("decimal(18,2)");

//                    b.Property<string>("RentalLocation")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ThumbNailImageUrl")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("Transmission")
//                        .HasColumnType("int");

//                    b.Property<int>("Year")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.ToTable("Cars");

//                    b.HasData(
//                        new
//                        {
//                            Id = "12ee631b-e38d-4cba-b6d3-b01e9fe72973",
//                            BodyStyle = "Sedan",
//                            Brand = "Toyota",
//                            Color = "Silver",
//                            Condition = 1,
//                            Description = "Embark on your next adventure in the 2022 Toyota Corolla, a reliable and well-maintained sedan in a classic silver finish. This vehicle offers a seamless blend of style, comfort, and technology, making it the perfect choice for both urban and highway driving. The Corolla is equipped with a fuel-efficient 1.8L engine, ensuring that your journeys are not only enjoyable but also eco-friendly. Inside, you'll find modern features, including Bluetooth connectivity for hands-free calling and music streaming, as well as a convenient backup camera to assist with parking and maneuvering in tight spaces. With seating for up to five passengers, it's an excellent choice for family trips or group outings. Despite being a used car, it feels like new, and you can enjoy all its perks for just $40 per day.",
//                            Features = "Air Conditioner,Bluetooth,Backup Camera",
//                            Gps = 0,
//                            ImageUrl = "https://i.pinimg.com/236x/74/61/4d/74614d884940788ce8d1a6ef46fcb8a9.jpg",
//                            LicensePlate = "ABC123",
//                            Mileage = 10000.0,
//                            Model = "Corolla",
//                            PricePerDay = 15000.00m,
//                            RentalLocation = "Downtown Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 1,
//                            Year = 2022
//                        },
//                        new
//                        {
//                            Id = "627c621c-fa4f-4942-9969-8982ea4d2c07",
//                            BodyStyle = "Coupe",
//                            Brand = "Ford",
//                            Color = "Red",
//                            Condition = 0,
//                            Description = "Unleash the power and sophistication of the 2023 Ford Mustang, a red-hot coupe designed for thrill-seekers and performance enthusiasts. This brand-new Mustang is the epitome of style, speed, and cutting-edge technology. Beneath the hood lies a potent 2.3L engine, offering a heart-pounding driving experience that's sure to ignite your passion for the road. The Mustang's manual transmission provides an intimate connection between driver and machine, making every gear shift a memorable experience. Whether you're planning a weekend getaway or simply want to make a statement, this Mustang is the perfect choice. For just $60 per day, you can commandeer this automotive marvel, available for rent starting from 09/02/2023 at our Airport Branch",
//                            Features = "Air Conditioner,Leather Seats,Apple CarPlay",
//                            Gps = 1,
//                            ImageUrl = "https://img.freepik.com/premium-vector/car_27088-93.jpg?w=826",
//                            LicensePlate = "DEF456",
//                            Mileage = 5000.0,
//                            Model = "Mustang",
//                            PricePerDay = 25080.00m,
//                            RentalLocation = "Airport Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 0,
//                            Year = 2023
//                        },
//                        new
//                        {
//                            Id = "2c2c07a2-54f2-4c48-aa2d-e142e4be7673",
//                            BodyStyle = "SUV",
//                            Brand = "Honda",
//                            Color = "Blue",
//                            Condition = 1,
//                            Description = "Experience the environmentally conscious driving pleasure of the 2021 Honda CR-V in a mesmerizing shade of blue. This well-maintained SUV is equipped with all-wheel drive, ensuring exceptional stability and control on diverse terrains. The spacious interior accommodates up to five passengers comfortably, making it ideal for family outings or group adventures. You'll find a sunroof that adds an extra touch of luxury and the opportunity to soak in the natural surroundings during your journey. Plus, with comprehensive insurance coverage, you can embark on your travels with confidence. Rent the 2021 Honda CR-V today for just $55 per day from our conveniently located suburb branch.",
//                            Features = "All-Wheel Drive,Air Conditioner,Sunroof",
//                            Gps = 0,
//                            ImageUrl = "https://img.freepik.com/premium-vector/realistic-vector-blue-city-car-coupe-sport-transportation-isolated-background_33869-3203.jpg?w=826",
//                            LicensePlate = "XYZ789",
//                            Mileage = 15000.0,
//                            Model = "CR-V",
//                            PricePerDay = 13789.00m,
//                            RentalLocation = "Suburb Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 1,
//                            Year = 2021
//                        },
//                        new
//                        {
//                            Id = "b2ca4f4e-b457-4ba4-a4e2-46b0b1957677",
//                            BodyStyle = "SUV",
//                            Brand = "Chevrolet",
//                            Color = "Black",
//                            Condition = 0,
//                            Description = "Elevate your travel experiences with the 2022 Chevrolet Tahoe, a commanding presence in sleek black. This full-size SUV is engineered for versatility, making it a perfect choice for family vacations and group getaways. Equipped with a robust 5.3L engine, the Tahoe offers ample power to tackle various terrains with ease. Inside, you'll discover the luxury of third-row seating, ensuring ample space for everyone on board. And to keep passengers entertained during long journeys, there's a rear entertainment system that's sure to keep the kids (and adults) engaged. For your peace of mind, the Tahoe comes with collision insurance coverage, so you can relax and enjoy your adventures. Rent this spacious and stylish SUV today for $85 per day from our city center branch.",
//                            Features = "Air Conditioner,Third-Row Seating,Rear Entertainment System",
//                            Gps = 0,
//                            ImageUrl = "https://img.freepik.com/premium-vector/car-illustration_74218-174.jpg?w=826",
//                            LicensePlate = "MNO102",
//                            Mileage = 8000.0,
//                            Model = "Tahoe",
//                            PricePerDay = 30090.00m,
//                            RentalLocation = "City Center Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 1,
//                            Year = 2022
//                        },
//                        new
//                        {
//                            Id = "8736f6ad-c695-4f5b-986c-8708d2f9dc60",
//                            BodyStyle = "Sedan",
//                            Brand = "Nissan",
//                            Color = "White",
//                            Condition = 0,
//                            Description = "Step into the future of driving with the 2023 Nissan Altima, a contemporary and efficient sedan in classic white. This new model is equipped with a fuel-efficient 2.5L engine and seamless Apple CarPlay integration, allowing you to stay connected and entertained on the road. Whether you're commuting to work or embarking on a weekend road trip, the Altima offers the perfect blend of comfort and convenience. With a spacious interior and a medium-sized luggage capacity, it's well-suited for urban explorations and beyond. Priced at just $45 per day, this stylish sedan is available for rent from our residential branch, making it an ideal choice for your next adventure.",
//                            Features = "Air Conditioner,Keyless Entry,Lane Departure Warning",
//                            Gps = 1,
//                            ImageUrl = "https://img.freepik.com/free-vector/white-sedan-car-isolated-white-vector_53876-67413.jpg?w=740&t=st=1693468993~exp=1693469593~hmac=85da748d4aaa3d7e6b355f713443f4d83c1b7657c921d615f0700aa0b2a91c24",
//                            LicensePlate = "PQR345",
//                            Mileage = 3500.0,
//                            Model = "Altima",
//                            PricePerDay = 12000.00m,
//                            RentalLocation = "Residential Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 2,
//                            Year = 2023
//                        },
//                        new
//                        {
//                            Id = "c19d0350-1ead-4d3c-a039-c8aa5eed1813",
//                            BodyStyle = "SUV",
//                            Brand = "BMW",
//                            Color = "Dark Grey",
//                            Condition = 1,
//                            Description = "Experience the epitome of luxury and performance with the 2022 BMW X5, a sophisticated SUV in a striking shade of dark gray. This vehicle is designed to impress, boasting a powerful 3.0L engine that delivers an exhilarating driving experience. Inside, you'll find a panoramic roof that bathes the cabin in natural light, creating an open and airy atmosphere. Whether you're planning a weekend getaway or a special occasion, the BMW X5 is ready to elevate your journey. It's like-new, meticulously maintained, and available for rent at $75 per day from our luxury branch. Treat yourself to the elegance and power of the BMW X5 today",
//                            Features = "Air Conditioner,Virtual Cockpit,Adaptive Cruise Control",
//                            Gps = 0,
//                            ImageUrl = "https://img.freepik.com/free-vector/black-sedan-car-isolated-white-vector_53876-64403.jpg?w=740&t=st=1693469071~exp=1693469671~hmac=e9294ad93de6cf4e47d7fcee1d010df6fd0c1c41b64dc6508bb1e91bcad4ea8b",
//                            LicensePlate = "STU678",
//                            Mileage = 12000.0,
//                            Model = "X5",
//                            PricePerDay = 27790.00m,
//                            RentalLocation = "Luxury Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 1,
//                            Year = 2022
//                        },
//                        new
//                        {
//                            Id = "ebdc2804-eac6-4704-8961-07dfadd5f3c9",
//                            BodyStyle = "Crossover",
//                            Brand = "Hyundai",
//                            Color = "Silver",
//                            Condition = 0,
//                            Description = "Navigate the city in style with the 2023 Hyundai Tucson, a versatile and feature-packed crossover in timeless silver. Designed to make your daily commute or urban exploration a breeze, this Hyundai offers seamless Apple CarPlay integration and advanced lane-keeping assist for added safety. With its medium luggage capacity and spacious interior, it's perfectly suited for both daily routines and spontaneous getaways. Priced at just $50 per day, it's an affordable choice for those seeking comfort, convenience, and modern technology. Rent the 2023 Hyundai Tucson today from our conveniently located urban branch and experience the best in contemporary driving.",
//                            Features = "Air Conditioner,Panoramic Roof,Advanced Driver Assistance",
//                            Gps = 1,
//                            ImageUrl = "https://img.freepik.com/free-vector/white-hatchback-car-isolated-white-vector_53876-67619.jpg?w=740&t=st=1693469151~exp=1693469751~hmac=42020cd6b47cea4989913352d633ee1f077224ae04331702d18a80b9978f4160",
//                            LicensePlate = "VWX901",
//                            Mileage = 4000.0,
//                            Model = "Tuscon",
//                            PricePerDay = 12900.00m,
//                            RentalLocation = "Urban Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 1,
//                            Year = 2023
//                        },
//                        new
//                        {
//                            Id = "8d228ee2-e685-4361-b9e3-60d71101632f",
//                            BodyStyle = "Sedan",
//                            Brand = "Mercedes Benz",
//                            Color = "Black",
//                            Condition = 1,
//                            Description = "Indulge in a world of sophistication and comfort with the 2021 Mercedes-Benz C-Class, an elegant black sedan that exudes luxury. This vehicle is designed for those who appreciate the finer things in life, with plush leather seats and a premium sound system that transforms your journeys into auditory delights. Its like-new condition ensures a smooth and worry-free driving experience. Whether you're planning a night out in the city or an important business meeting, the C-Class is the perfect choice to make a lasting impression. Available for rent at $65 per day from our downtown branch, it's your ticket to arriving in style and comfort",
//                            Features = "Air Conditioner,Apple CarPlay,Lane Keeping Assistance",
//                            Gps = 0,
//                            ImageUrl = "https://img.freepik.com/free-vector/black-sedan-car-isolated-white-vector_53876-64403.jpg?w=740&t=st=1693469250~exp=1693469850~hmac=f3510a48665977358efbfbbb4feda40e4219fbb151376d0201abff0be083f5e0",
//                            LicensePlate = "XYZ234",
//                            Mileage = 9000.0,
//                            Model = "C-Class",
//                            PricePerDay = 18000.00m,
//                            RentalLocation = "Downtown Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 1,
//                            Year = 2021
//                        },
//                        new
//                        {
//                            Id = "57c4c993-b063-43c9-b7ce-0763da78f227",
//                            BodyStyle = "Wagon",
//                            Brand = "Subaru",
//                            Color = "Green",
//                            Condition = 0,
//                            Description = "Embrace the spirit of adventure with the 2023 Subaru Outback, a vibrant green wagon that's ready to tackle any terrain. With its all-wheel-drive capability and roof rack, this Subaru is your go-to companion for outdoor escapades. Whether you're planning a camping trip, a scenic road journey, or simply need extra cargo space, the Outback has got you covered. This like-new wagon is priced at an affordable $55 per day and is available for rent from our convenient suburb branch. Don't miss the opportunity to explore the great outdoors in style and comfort with the 2023 Subaru Outback",
//                            Features = "Air Conditioner,Leather Seats,Premium Sound System",
//                            Gps = 0,
//                            ImageUrl = "https://img.freepik.com/premium-vector/realistic-green-sport-two-tone-luxury-car-set-grey-metallic-background-vector_33869-3705.jpg?w=826",
//                            LicensePlate = "ABC567",
//                            Mileage = 2500.0,
//                            Model = "Outback",
//                            PricePerDay = 13000.00m,
//                            RentalLocation = "Suburb Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 2,
//                            Year = 2023
//                        },
//                        new
//                        {
//                            Id = "7d25bc24-ba01-4a9b-9548-810a919b2a62",
//                            BodyStyle = "Sedan",
//                            Brand = "Audi",
//                            Color = "Blue",
//                            Condition = 1,
//                            Description = "Elevate your airport arrival experience with the 2022 Audi A4, a sleek and stylish blue sedan that blends performance with sophistication. The Audi A4 boasts an advanced Virtual Cockpit and adaptive cruise control, ensuring that your journey is both technologically advanced and comfortable. Whether you're arriving in town for a business meeting or embarking on a leisurely vacation, this Audi offers the perfect blend of luxury and practicality. It's like-new, meticulously maintained, and available for rent at $70 per day from our airport branch. Treat yourself to the Audi experience and make your arrival memorable",
//                            Features = "Air Conditioner,All-Wheel Drive,Roof Rack",
//                            Gps = 1,
//                            ImageUrl = "https://img.freepik.com/free-vector/blue-hatchback-car-isolated-white-vector_53876-67408.jpg?w=740&t=st=1693469399~exp=1693469999~hmac=32c8b4fcec147544bfb4919c72de1bc1229d202c4bd18741bdcb065f908b2be3",
//                            LicensePlate = "DEF678",
//                            Mileage = 7500.0,
//                            Model = "A4",
//                            PricePerDay = 28470.00m,
//                            RentalLocation = "Airport Branch",
//                            ThumbNailImageUrl = "https://i.pinimg.com/236x/25/e7/e4/25e7e47750265a7bdc3b6eb49785e5cb.jpg",
//                            Transmission = 1,
//                            Year = 2022
//                        });
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Name")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("NormalizedName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.HasKey("Id");

//                    b.HasIndex("NormalizedName")
//                        .IsUnique()
//                        .HasDatabaseName("RoleNameIndex")
//                        .HasFilter("[NormalizedName] IS NOT NULL");

//                    b.ToTable("AspNetRoles");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("RoleId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("Id");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetRoleClaims");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<int>("AccessFailedCount")
//                        .HasColumnType("int");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Email")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<bool>("EmailConfirmed")
//                        .HasColumnType("bit");

//                    b.Property<bool>("LockoutEnabled")
//                        .HasColumnType("bit");

//                    b.Property<DateTimeOffset?>("LockoutEnd")
//                        .HasColumnType("datetimeoffset");

//                    b.Property<string>("NormalizedEmail")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("NormalizedUserName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("PasswordHash")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("PhoneNumber")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("PhoneNumberConfirmed")
//                        .HasColumnType("bit");

//                    b.Property<string>("SecurityStamp")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("TwoFactorEnabled")
//                        .HasColumnType("bit");

//                    b.Property<string>("UserName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.HasKey("Id");

//                    b.HasIndex("NormalizedEmail")
//                        .HasDatabaseName("EmailIndex");

//                    b.HasIndex("NormalizedUserName")
//                        .IsUnique()
//                        .HasDatabaseName("UserNameIndex")
//                        .HasFilter("[NormalizedUserName] IS NOT NULL");

//                    b.ToTable("AspNetUsers");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("Id");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserClaims");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                {
//                    b.Property<string>("LoginProvider")
//                        .HasMaxLength(128)
//                        .HasColumnType("nvarchar(128)");

//                    b.Property<string>("ProviderKey")
//                        .HasMaxLength(128)
//                        .HasColumnType("nvarchar(128)");

//                    b.Property<string>("ProviderDisplayName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("LoginProvider", "ProviderKey");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserLogins");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                {
//                    b.Property<string>("UserId")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("RoleId")
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("UserId", "RoleId");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetUserRoles");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                {
//                    b.Property<string>("UserId")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("LoginProvider")
//                        .HasMaxLength(128)
//                        .HasColumnType("nvarchar(128)");

//                    b.Property<string>("Name")
//                        .HasMaxLength(128)
//                        .HasColumnType("nvarchar(128)");

//                    b.Property<string>("Value")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("UserId", "LoginProvider", "Name");

//                    b.ToTable("AspNetUserTokens");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
